name: Bump go4.org/unsafe/assume-no-moving-gc

on:
  push:
  schedule:
    - cron: '0 0 * * *' # daily

defaults:
  run:
    shell: nix develop -c bash -e {0}

jobs:
  bump:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Tidy up Go modules
        run: go mod tidy

      - name: Bump go4.org/unsafe/assume-no-moving-gc
        run: |
          (
            cd pkg
            go get -u go4.org/unsafe/assume-no-moving-gc
            go mod tidy
          )

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump go4.org/unsafe/assume-no-moving-gc
